# Generated by Django 6.0.2 on 2026-02-19 09:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditlogs',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('target_entity', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'auditlogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grantcycles',
            fields=[
                ('cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cycle_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('stage1_start_date', models.DateField(blank=True, null=True)),
                ('stage1_end_date', models.DateField(blank=True, null=True)),
                ('revision_duration_days', models.IntegerField(blank=True, null=True)),
                ('stage2_start_date', models.DateField(blank=True, null=True)),
                ('stage2_end_date', models.DateField(blank=True, null=True)),
                ('acceptance_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_reviewers_per_proposal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grantcycles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proposaldocuments',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=8)),
                ('file_path', models.CharField(max_length=255)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'proposaldocuments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('co_investigators', models.TextField(blank=True, null=True)),
                ('fund_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=26)),
                ('stage1_decision', models.CharField(blank=True, max_length=9, null=True)),
                ('stage1_decision_date', models.DateTimeField(blank=True, null=True)),
                ('stage1_remarks', models.TextField(blank=True, null=True)),
                ('final_decision', models.CharField(blank=True, max_length=8, null=True)),
                ('final_grant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proposals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewassignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField()),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviewassignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewers',
            fields=[
                ('reviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_of_expertise', models.TextField(blank=True, null=True)),
                ('max_review_load', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviewers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrcChairs',
            fields=[
                ('src_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'src_chairs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage1Reviews',
            fields=[
                ('stage1_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_originality', models.IntegerField(blank=True, null=True)),
                ('score_clarity', models.IntegerField(blank=True, null=True)),
                ('score_lit_review', models.IntegerField(blank=True, null=True)),
                ('score_methodology', models.IntegerField(blank=True, null=True)),
                ('score_impact', models.IntegerField(blank=True, null=True)),
                ('score_publication', models.IntegerField(blank=True, null=True)),
                ('score_budget', models.IntegerField(blank=True, null=True)),
                ('score_timeframe', models.IntegerField(blank=True, null=True)),
                ('total_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('narrative_comments', models.TextField(blank=True, null=True)),
                ('is_submitted', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stage1reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage2Reviews',
            fields=[
                ('stage2_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('concerns_addressed', models.CharField(max_length=9)),
                ('recommendation', models.CharField(max_length=6)),
                ('revised_score', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'stage2reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
